### ISSUE TITLE
Upload code

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-php#1]
@agcbianchi Can I upload the code to the public repository? No images. No SQL dump.

You **only** have private repos after upgrade to the paid plan.

![new-repository](https://user-images.githubusercontent.com/1506457/76921518-045c2500-68ad-11ea-935a-720c8ea7e26d.png)

**Comment by andrea-g-campos** [comment]
Sim Raniere, sem problemas

Em qua, 18 de mar de 2020 00:12, Raniere Silva <notifications@github.com>
escreveu:

**Comment by rgaiacs** [comment]
Done.

I also included a README.

**Comment by andrea-g-campos** [comment]
Wonderful !! thanks !
